(import (rnrs) (srfi :230) (async) (test))

;; Multiple async tasks swap values into the same box
(let ((box (make-atomic-box 0)))
  (define (writer id n)
    (lambda ()
      (let loop ((i 0))
        (when (< i n)
          (atomic-box-swap! box (+ (* id 1000) i))
          (loop (+ i 1))))))

  (let ((f1 (spawn (writer 1 100)))
        (f2 (spawn (writer 2 100)))
        (f3 (spawn (writer 3 100))))
    (await f1)
    (await f2)
    (await f3)
    (assert-equal? (number? (atomic-box-ref box)) #t)))

;; Concurrent CAS — at most one task should win per attempt
(let ((box (make-atomic-box 'initial)))
  (let ((f1 (spawn (lambda ()
                      (atomic-box-compare-and-swap! box 'initial 'task-1))))
        (f2 (spawn (lambda ()
                      (atomic-box-compare-and-swap! box 'initial 'task-2)))))
    (await f1)
    (await f2)
    (let ((final-val (atomic-box-ref box)))
      (assert-equal? (or (eq? final-val 'task-1)
                         (eq? final-val 'task-2))
                     #t))))

;; Concurrent readers and writers with GC-managed values
(let ((box (make-atomic-box (list 'start))))
  (define (reader n)
    (lambda ()
      (let loop ((i 0))
        (when (< i n)
          (let ((v (atomic-box-ref box)))
            (assert-equal? (pair? v) #t))
          (loop (+ i 1))))))

  (let ((fw (spawn (lambda ()
                      (let loop ((i 0))
                        (when (< i 50)
                          (atomic-box-set! box (list i))
                          (loop (+ i 1)))))))
        (fr1 (spawn (reader 50)))
        (fr2 (spawn (reader 50))))
    (await fw)
    (await fr1)
    (await fr2)
    (assert-equal? (pair? (atomic-box-ref box)) #t)))
