(library (rnrs (6))
  (export (import (rnrs base (6)))
          (import (rnrs syntax-case (6)))
          (import (rnrs hashtables (6)))
          (import (rnrs records syntactic (6)))
          (import (rnrs records procedural (6)))
          (import (rnrs records inspection (6)))))
